on:
  push:
    tags:
      - v*.*

# on:
#   push:

jobs:
  build:
    name: Collect and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: sophgo/tpuc_dev:latest
      volumes:
        - /github/workspace:/workspace/tpu-mlir/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add safe.directory
      run: sudo git config --global --add safe.directory /__w/tpu-mlir-test-workflow/tpu-mlir-test-workflow

    - name: Check dirs
      run: pwd && ls

    - name: Run Docker container
      run: |
        . release_pip.sh

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./dist/

  check-ccache:
      needs: build
      name: Check ccache
      runs-on: ubuntu-latest
      steps:
      - name: Check ccache dir
        run: |
          pwd
          ls
          find / -name ccache

  pypi-publish:
      needs: build
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/tpu_mlir_test
      permissions:
        contents: write
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      - name: Make dist dir
        run: |
          mkdir dist && cd dist
          ls

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./dist/
    
      - name: Display structure of downloaded files
        run: |
          pwd
          ls
          cd dist
          ls

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/*.whl
          # token: ${{ secrets.tpu_mlir_test }}
