
on:
  push:

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull sophgo/tpuc_dev:latest

    - name: Run Docker container
      run: |
        docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:latest /bin/bash -c "
          apt-get update
          apt-get install patchelf
          apt-get install python3.10-dev
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
          python -m pip install --upgrade pip setuptools
          . release_pip.sh
        "
    - name: Publish tpu_mlir package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
