
on:
  push:

jobs:
  build:
    name: Collect and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: sophgo/tpuc_dev:latest
      volumes:
        - /github/workspace:/workspace/tpu-mlir/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check dirs
      run: pwd && ls

    - name: Run Docker container
      run: |
        apt-get update
        apt-get install patchelf
        apt-get install python3.10-dev
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install --upgrade twine
        python -m pip install --upgrade pip setuptools
        ls
        . release_pip.sh
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./dist/

  pypi-publish:
      needs: build
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/tpu_mlir_test
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      - name: Make dist dir
        run: |
          mkdir dist && cd dist
          ls

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./dist/
    
      - name: Display structure of downloaded files
        run: |
          pwd
          ls
          cd dist
          ls
        
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
